name: CI Pre-build
run-name: Test project before building ${{ github.actor }}

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_REGION: eu-west-1

jobs:
  pre:
    name: .pre
    runs-on: ubuntu-22.04

    steps:
      - name: Build information
        run: |
          echo "The job was automatically triggered by a ${{ github.event_name }} event." && \
          echo "This job is now running on a ${{ runner.os }}!" && \
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

  check:
    name: Analyze code
    runs-on: ubuntu-22.04
    needs: [ pre ]
    container:
      image: node:18.12.1

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: List files in the repository
        run: "ls -la"

      - name: Audit modules
        run: npm audit --audit-level critical

      - name: Prepare
        run: npm i --omit=dev --ignore-scripts

      - name: Check prettiness of the code
        run: npx prettier -c "src/**/*.ts"

      - name: Lint the code
        run: npx eslint "src/**/*.ts" -f json -o .report/eslint.json

      - name: Build
        run: npm run build

      - name: Run Unit-tests
        run: npm run test:cov

      - name: SonarQube Analyzer
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Failer
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  post:
    name: .post
    runs-on: ubuntu-22.04
    needs: [pre, check]

    steps:
      - name: Pre job results
        run: echo "Checking has finished"
